### Acessando via GET
GET http://localhost:3000/subscribers
### 
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "userName": "José da Silva",
    "userChannel": "hcodebrasil"
}
###
GET http://localhost:3000/subscribers/5e9bbed7c063ce3b2075eda2
###
DELETE http://localhost:3000/subscribers/5e9bbed7c063ce3b2075eda2
###